"""
PREDICT - Vehicle Intelligence Platform
Copyright © 2026 PREDICT
All rights reserved.

This file is proprietary and confidential.
Unauthorized copying, modification, distribution, or use is strictly prohibited.

Created: January 2026
Module: Enhanced Pdf Generator

Enhanced PDF Report Generator
Commercial-grade PDF reports with:
- Legal disclaimers
- Model version attribution
- Confidence scores
- Report versioning
- Tamper-resistant metadata
"""

import json
import hashlib
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


# Legal disclaimer text
LEGAL_DISCLAIMER = """
IMPORTANT LEGAL DISCLAIMER

This report is generated by PredictOBD AI system and is provided for informational purposes only.
The predictions, assessments, and recommendations contained in this report are based on statistical
models and historical data analysis.

LIMITATIONS AND DISCLAIMERS:
• AI predictions are probabilistic and not guaranteed to be accurate
• Actual vehicle condition may differ from predictions
• This report does NOT replace professional mechanical inspection
• Always consult qualified automotive professionals for maintenance decisions
• PredictOBD is not liable for decisions made based on this report
• Confidence scores indicate model certainty, not absolute accuracy
• Report accuracy depends on data quality and completeness

For critical safety decisions, always seek professional inspection. By using this report, you
acknowledge these limitations and agree that PredictOBD bears no responsibility for outcomes
resulting from reliance on this information.

Report Version: {report_version}
Model Version: {model_version}
Generated: {generated_at}
Report ID: {report_id}
Checksum: {checksum}
"""


class EnhancedPDFGenerator:
    """
    Commercial-grade PDF report generator.

    Features:
    - Legal disclaimers
    - Model attribution
    - Confidence display
    - Version tracking
    - Tamper detection
    """

    def __init__(self):
        if not REPORTLAB_AVAILABLE:
            raise ImportError("reportlab required for PDF generation")

    def generate_vehicle_health_report(
        self,
        customer_id: str,
        vehicle_id: str,
        vehicle_data: Dict[str, Any],
        predictions: Dict[str, Any],
        model_version: str,
        confidence_scores: Dict[str, float],
        output_path: Path
    ) -> Tuple[bool, Optional[str], Optional[Dict[str, Any]]]:
        """
        Generate comprehensive vehicle health PDF report.

        Args:
            customer_id: Customer ID
            vehicle_id: Vehicle ID
            vehicle_data: Vehicle information
            predictions: AI predictions
            model_version: AI model version used
            confidence_scores: Confidence for each prediction
            output_path: Where to save PDF

        Returns:
            (success, error_message, report_metadata)
        """
        try:
            # Generate report metadata
            report_id = self._generate_report_id()
            report_version = "1.0"
            generated_at = datetime.now().isoformat()

            # Create document
            doc = SimpleDocTemplate(
                str(output_path),
                pagesize=letter,
                rightMargin=0.75*inch,
                leftMargin=0.75*inch,
                topMargin=0.75*inch,
                bottomMargin=0.75*inch
            )

            # Build content
            elements = []
            styles = getSampleStyleSheet()

            # Title page
            elements.extend(self._create_title_page(vehicle_data, report_id, styles))

            # Legal disclaimer
            elements.extend(self._create_disclaimer_page(
                report_version, model_version, generated_at, report_id, styles
            ))

            # Vehicle information
            elements.extend(self._create_vehicle_info_section(vehicle_data, styles))

            # AI Predictions with confidence
            elements.extend(self._create_predictions_section(
                predictions, confidence_scores, model_version, styles
            ))

            # Model attribution
            elements.extend(self._create_model_attribution_section(model_version, styles))

            # Footer with metadata
            elements.extend(self._create_footer(report_id, report_version, generated_at, styles))

            # Build PDF
            doc.build(elements)

            # Calculate report checksum
            checksum = self._calculate_pdf_checksum(output_path)

            # Create metadata
            metadata = {
                "report_id": report_id,
                "report_version": report_version,
                "customer_id": customer_id,
                "vehicle_id": vehicle_id,
                "model_version": model_version,
                "generated_at": generated_at,
                "file_path": str(output_path),
                "checksum": checksum,
                "confidence_scores": confidence_scores
            }

            # Save metadata
            self._save_report_metadata(metadata)

            return True, None, metadata

        except Exception as e:
            return False, f"PDF generation failed: {str(e)}", None

    def _create_title_page(self, vehicle_data: Dict[str, Any], report_id: str, styles) -> list:
        """Create title page"""
        elements = []

        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=28,
            alignment=TA_CENTER,
            spaceAfter=30,
            textColor=colors.HexColor('#1a237e')
        )

        elements.append(Spacer(1, 2*inch))
        elements.append(Paragraph("PredictOBD", title_style))
        elements.append(Paragraph("Vehicle Health & Predictive Maintenance Report",
                                 ParagraphStyle('Subtitle', parent=title_style, fontSize=16, spaceAfter=20)))

        elements.append(Spacer(1, inch))

        # Vehicle details
        vehicle_info = [
            ["Vehicle:", vehicle_data.get("make", "") + " " + vehicle_data.get("model", "")],
            ["Year:", str(vehicle_data.get("year", ""))],
            ["VIN:", vehicle_data.get("vin", "N/A")],
            ["Report ID:", report_id],
            ["Generated:", datetime.now().strftime("%B %d, %Y at %H:%M:%S")]
        ]

        table = Table(vehicle_info, colWidths=[1.5*inch, 4*inch])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(table)

        elements.append(PageBreak())

        return elements

    def _create_disclaimer_page(
        self,
        report_version: str,
        model_version: str,
        generated_at: str,
        report_id: str,
        styles
    ) -> list:
        """Create legal disclaimer page"""
        elements = []

        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=9,
            alignment=TA_JUSTIFY,
            leading=12
        )

        # Calculate checksum placeholder
        checksum = "CALCULATED_AFTER_GENERATION"

        disclaimer_text = LEGAL_DISCLAIMER.format(
            report_version=report_version,
            model_version=model_version,
            generated_at=generated_at,
            report_id=report_id,
            checksum=checksum
        )

        elements.append(Paragraph(disclaimer_text, disclaimer_style))
        elements.append(PageBreak())

        return elements

    def _create_vehicle_info_section(self, vehicle_data: Dict[str, Any], styles) -> list:
        """Create vehicle information section"""
        elements = []

        heading_style = ParagraphStyle(
            'Heading',
            parent=styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#283593')
        )

        elements.append(Paragraph("Vehicle Information", heading_style))

        info_data = [
            ["Make:", vehicle_data.get("make", "N/A")],
            ["Model:", vehicle_data.get("model", "N/A")],
            ["Year:", str(vehicle_data.get("year", "N/A"))],
            ["VIN:", vehicle_data.get("vin", "N/A")],
            ["Mileage:", f"{vehicle_data.get('mileage', 0):,} km"],
            ["Engine Type:", vehicle_data.get("engine_type", "N/A")],
            ["Fuel Type:", vehicle_data.get("fuel_type", "N/A")],
        ]

        table = Table(info_data, colWidths=[2*inch, 4*inch])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 20))

        return elements

    def _create_predictions_section(
        self,
        predictions: Dict[str, Any],
        confidence_scores: Dict[str, float],
        model_version: str,
        styles
    ) -> list:
        """Create AI predictions section with confidence scores"""
        elements = []

        heading_style = ParagraphStyle(
            'Heading',
            parent=styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#283593')
        )

        elements.append(Paragraph("AI Predictions & Risk Assessment", heading_style))
        elements.append(Paragraph(
            f"<b>Model Version:</b> {model_version}",
            styles['Normal']
        ))
        elements.append(Spacer(1, 10))

        # Predictions table with confidence
        pred_data = [["Prediction", "Result", "Confidence", "Status"]]

        for pred_name, pred_value in predictions.items():
            confidence = confidence_scores.get(pred_name, 0.0)

            # Color code confidence
            if confidence >= 0.8:
                status = "High Confidence"
                color = colors.green
            elif confidence >= 0.6:
                status = "Medium Confidence"
                color = colors.orange
            else:
                status = "Low Confidence"
                color = colors.red

            pred_data.append([
                pred_name,
                str(pred_value),
                f"{confidence:.1%}",
                status
            ])

        table = Table(pred_data, colWidths=[2.5*inch, 1.5*inch, 1*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e8eaf6')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1a237e')),
            ('ALIGN', (2, 0), (2, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(table)

        # Confidence explanation
        elements.append(Spacer(1, 15))
        elements.append(Paragraph(
            "<b>Confidence Score Interpretation:</b>",
            styles['Normal']
        ))
        elements.append(Paragraph(
            "• High (>80%): Strong confidence in prediction<br/>"
            "• Medium (60-80%): Moderate confidence, monitor closely<br/>"
            "• Low (<60%): Limited confidence, seek professional assessment",
            styles['Normal']
        ))

        elements.append(Spacer(1, 20))

        return elements

    def _create_model_attribution_section(self, model_version: str, styles) -> list:
        """Create model attribution section"""
        elements = []

        elements.append(Paragraph(
            f"<b>AI Model Information</b>",
            styles['Heading3']
        ))
        elements.append(Paragraph(
            f"This report was generated using PredictOBD AI Model <b>Version {model_version}</b>. "
            f"The model was trained on anonymized vehicle maintenance data and uses machine learning "
            f"algorithms to predict potential issues. Model predictions should be used as guidance "
            f"alongside professional mechanical assessment.",
            styles['Normal']
        ))
        elements.append(Spacer(1, 20))

        return elements

    def _create_footer(self, report_id: str, report_version: str, generated_at: str, styles) -> list:
        """Create report footer with metadata"""
        elements = []

        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            alignment=TA_CENTER
        )

        elements.append(Spacer(1, 40))
        elements.append(Paragraph(
            f"Report ID: {report_id} | Version: {report_version} | "
            f"Generated: {generated_at}<br/>"
            f"PredictOBD - Predictive Vehicle Maintenance | predict.previlium.com",
            footer_style
        ))

        return elements

    def _calculate_pdf_checksum(self, pdf_path: Path) -> str:
        """Calculate PDF checksum for tamper detection"""
        hash_obj = hashlib.sha256()

        with open(pdf_path, 'rb') as f:
            while chunk := f.read(8192):
                hash_obj.update(chunk)

        return hash_obj.hexdigest()

    def _save_report_metadata(self, metadata: Dict[str, Any]):
        """Save report metadata for tracking"""
        from config import get_config
        config = get_config()

        metadata_dir = config.REPORTS_METADATA_DIR
        metadata_dir.mkdir(parents=True, exist_ok=True)

        metadata_file = metadata_dir / f"{metadata['report_id']}.json"

        with open(metadata_file, 'w') as f:
            json.dump(metadata, f, indent=2)

    def _generate_report_id(self) -> str:
        """Generate unique report ID"""
        import secrets
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        random_suffix = secrets.token_hex(4)
        return f"rpt_{timestamp}_{random_suffix}"


# ==================== MODULE-LEVEL FUNCTIONS ====================

def generate_commercial_pdf(
    customer_id: str,
    vehicle_id: str,
    vehicle_data: Dict[str, Any],
    predictions: Dict[str, Any],
    model_version: str,
    confidence_scores: Dict[str, float],
    output_path: Path
) -> Tuple[bool, Optional[str], Optional[Dict[str, Any]]]:
    """Convenience function for generating commercial PDFs"""
    generator = EnhancedPDFGenerator()
    return generator.generate_vehicle_health_report(
        customer_id, vehicle_id, vehicle_data, predictions,
        model_version, confidence_scores, output_path
    )
