"""
PREDICT - Vehicle Intelligence Platform
Copyright © 2026 PREDICT
All rights reserved.

This file is proprietary and confidential.
Unauthorized copying, modification, distribution, or use is strictly prohibited.

Created: January 2026
Module: Safety Disclaimer Manager

Safety Disclaimer Manager
=========================
Manages and enforces safety disclaimers throughout the application.
Ensures users are properly informed about prediction limitations.

CRITICAL: All predictions MUST be accompanied by appropriate disclaimers.
This is a legal and safety requirement.
"""

import json
import hashlib
import logging
from typing import Dict, Any, Optional, List, Tuple
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from enum import Enum

logger = logging.getLogger(__name__)


# =============================================================================
# DISCLAIMER TYPES AND TEMPLATES
# =============================================================================

class DisclaimerType(Enum):
    """Types of disclaimers."""
    GENERAL = "general"                    # Always shown
    PREDICTION = "prediction"              # Shown with predictions
    CRITICAL_FAILURE = "critical_failure"  # For safety-critical predictions
    LOW_CONFIDENCE = "low_confidence"      # For low confidence predictions
    UNSUPPORTED_VEHICLE = "unsupported_vehicle"  # For unsupported vehicles
    EXPERIMENTAL = "experimental"          # For experimental features
    LEGAL = "legal"                        # Legal disclaimer
    PROFESSIONAL_ADVICE = "professional"   # Professional inspection advice


class DisclaimerSeverity(Enum):
    """Severity level of disclaimer."""
    CRITICAL = "critical"    # Must be acknowledged, blocks action
    WARNING = "warning"      # Should be acknowledged
    INFO = "info"            # Informational
    LEGAL = "legal"          # Legal requirement


# =============================================================================
# DISCLAIMER TEMPLATES
# =============================================================================

DISCLAIMER_TEMPLATES = {
    DisclaimerType.GENERAL: {
        'title': "AI Prediction Disclaimer",
        'severity': DisclaimerSeverity.INFO,
        'text': """
This application uses artificial intelligence to analyze vehicle data and
predict potential failures. These predictions are based on pattern recognition
and statistical models trained on historical data.

IMPORTANT: AI predictions are NOT a substitute for professional automotive
diagnosis. Always consult a qualified mechanic for vehicle safety concerns.
""",
        'must_acknowledge': False,
        'show_frequency': 'once_per_session'
    },

    DisclaimerType.PREDICTION: {
        'title': "Prediction Notice",
        'severity': DisclaimerSeverity.INFO,
        'text': """
This prediction is generated by an AI model based on your vehicle's sensor data.

• Predictions are probabilistic estimates, not certainties
• Accuracy varies by vehicle type and condition
• Always verify with professional diagnosis
• Do not ignore manufacturer recommended maintenance
""",
        'must_acknowledge': False,
        'show_frequency': 'with_each_prediction'
    },

    DisclaimerType.CRITICAL_FAILURE: {
        'title': "⚠️ SAFETY-CRITICAL PREDICTION",
        'severity': DisclaimerSeverity.CRITICAL,
        'text': """
IMPORTANT SAFETY NOTICE

This prediction involves a SAFETY-CRITICAL vehicle system:
{failure_type}

Potential failure of this system could result in:
• Loss of vehicle control
• Stranding in dangerous conditions
• Damage to other vehicle systems
• Personal injury risk

REQUIRED ACTION:
1. Have your vehicle inspected by a certified mechanic IMMEDIATELY
2. Do NOT rely solely on this AI prediction
3. If you notice any unusual symptoms, stop driving and seek help

This AI prediction is advisory only and may not detect all issues.
Professional inspection is MANDATORY for safety-critical systems.
""",
        'must_acknowledge': True,
        'show_frequency': 'always'
    },

    DisclaimerType.LOW_CONFIDENCE: {
        'title': "Low Confidence Prediction",
        'severity': DisclaimerSeverity.WARNING,
        'text': """
⚠️ LOW CONFIDENCE PREDICTION

The confidence level for this prediction is below normal thresholds.

Reasons may include:
• Limited data for your specific vehicle
• Unusual sensor readings
• Insufficient historical patterns
• Data quality issues

Confidence: {confidence}%

This prediction should be treated as speculative. Professional diagnosis
is strongly recommended before taking any action.
""",
        'must_acknowledge': True,
        'show_frequency': 'always'
    },

    DisclaimerType.UNSUPPORTED_VEHICLE: {
        'title': "⚠️ UNSUPPORTED VEHICLE",
        'severity': DisclaimerSeverity.CRITICAL,
        'text': """
IMPORTANT: YOUR VEHICLE IS NOT IN OUR TRAINING DATABASE

Vehicle: {year} {make} {model}

Our AI model has NOT been trained on data from this specific vehicle.
Predictions are extrapolated from similar vehicles and may be:
• Less accurate
• Missing vehicle-specific failure patterns
• Based on assumptions that may not apply

RECOMMENDATION:
• Treat all predictions as low-confidence
• Always verify with a mechanic familiar with your vehicle
• Do not delay professional inspection based on AI predictions

We are continuously expanding our vehicle coverage. Check our documentation
for the list of fully supported vehicles.
""",
        'must_acknowledge': True,
        'show_frequency': 'always'
    },

    DisclaimerType.EXPERIMENTAL: {
        'title': "Experimental Feature",
        'severity': DisclaimerSeverity.WARNING,
        'text': """
🔬 EXPERIMENTAL FEATURE

This feature is currently in experimental/beta status.

• Results may be less reliable than production features
• Behavior may change in future updates
• Not recommended for critical decisions
• Please report any issues to help improve the system

Use at your own discretion and always verify important findings.
""",
        'must_acknowledge': True,
        'show_frequency': 'once_per_feature'
    },

    DisclaimerType.LEGAL: {
        'title': "Legal Disclaimer",
        'severity': DisclaimerSeverity.LEGAL,
        'text': """
LEGAL DISCLAIMER AND TERMS OF USE

By using this vehicle predictive maintenance system, you acknowledge and agree:

1. NO WARRANTY: This software is provided "AS IS" without warranty of any kind,
   express or implied, including but not limited to warranties of merchantability
   or fitness for a particular purpose.

2. NOT PROFESSIONAL ADVICE: Predictions generated by this system do NOT constitute
   professional automotive advice, diagnosis, or repair recommendations.

3. LIMITATION OF LIABILITY: The developers and operators of this system shall not
   be liable for any damages, injuries, or losses arising from use of or reliance
   on predictions generated by this system.

4. USER RESPONSIBILITY: You are solely responsible for:
   - Maintaining your vehicle according to manufacturer guidelines
   - Seeking professional inspection for any safety concerns
   - All decisions regarding vehicle operation and maintenance

5. PROFESSIONAL INSPECTION REQUIRED: All safety-critical predictions MUST be
   verified by a qualified automotive professional before any action is taken.

6. DATA ACCURACY: While we strive for accuracy, AI predictions are based on
   statistical models and may not reflect your specific vehicle's condition.

By continuing to use this application, you acknowledge that you have read,
understood, and agree to these terms.
""",
        'must_acknowledge': True,
        'show_frequency': 'on_first_use'
    },

    DisclaimerType.PROFESSIONAL_ADVICE: {
        'title': "Professional Inspection Recommended",
        'severity': DisclaimerSeverity.WARNING,
        'text': """
PROFESSIONAL INSPECTION RECOMMENDED

Based on this prediction, we recommend having your vehicle inspected by a
qualified automotive technician.

When visiting a mechanic, share:
• The specific prediction: {prediction_summary}
• The confidence level: {confidence}%
• Any symptoms you've noticed
• Your vehicle's maintenance history

Remember: This AI prediction is a tool to help identify potential issues,
not a definitive diagnosis. A trained professional with physical access to
your vehicle can provide accurate assessment.
""",
        'must_acknowledge': False,
        'show_frequency': 'with_each_prediction'
    }
}


# =============================================================================
# DATA STRUCTURES
# =============================================================================

@dataclass
class Disclaimer:
    """A disclaimer to be displayed to the user."""
    disclaimer_id: str
    disclaimer_type: DisclaimerType
    severity: DisclaimerSeverity
    title: str
    text: str
    must_acknowledge: bool
    context: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class DisclaimerAcknowledgment:
    """Record of user acknowledging a disclaimer."""
    acknowledgment_id: str
    disclaimer_id: str
    disclaimer_type: str
    user_id: str
    acknowledged_at: str
    ip_address: Optional[str] = None
    device_info: Optional[str] = None


# =============================================================================
# SAFETY DISCLAIMER MANAGER
# =============================================================================

class SafetyDisclaimerManager:
    """
    Manages safety disclaimers throughout the application.

    CRITICAL: This system ensures all predictions are accompanied by
    appropriate disclaimers. Disabling or bypassing disclaimers is
    a safety violation.
    """

    def __init__(self, storage_path: Optional[Path] = None):
        """Initialize disclaimer manager."""
        self.storage_path = storage_path or Path("ai_data/disclaimers")
        self.storage_path.mkdir(parents=True, exist_ok=True)

        self.templates = DISCLAIMER_TEMPLATES
        self._acknowledgments: Dict[str, DisclaimerAcknowledgment] = {}
        self._session_shown: set = set()

        self._load_acknowledgments()

        logger.info("Safety Disclaimer Manager initialized")

    def _load_acknowledgments(self):
        """Load previous acknowledgments."""
        ack_file = self.storage_path / "acknowledgments.json"
        if ack_file.exists():
            try:
                with open(ack_file, 'r') as f:
                    data = json.load(f)
                    for ack_data in data.get('acknowledgments', []):
                        ack = DisclaimerAcknowledgment(**ack_data)
                        key = f"{ack.user_id}:{ack.disclaimer_type}"
                        self._acknowledgments[key] = ack
            except Exception as e:
                logger.warning(f"Failed to load acknowledgments: {e}")

    def _save_acknowledgments(self):
        """Save acknowledgments to file."""
        ack_file = self.storage_path / "acknowledgments.json"
        try:
            data = {
                'acknowledgments': [
                    {
                        'acknowledgment_id': a.acknowledgment_id,
                        'disclaimer_id': a.disclaimer_id,
                        'disclaimer_type': a.disclaimer_type,
                        'user_id': a.user_id,
                        'acknowledged_at': a.acknowledged_at,
                        'ip_address': a.ip_address,
                        'device_info': a.device_info
                    }
                    for a in self._acknowledgments.values()
                ]
            }
            with open(ack_file, 'w') as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            logger.warning(f"Failed to save acknowledgments: {e}")

    def get_disclaimer(
        self,
        disclaimer_type: DisclaimerType,
        context: Optional[Dict[str, Any]] = None
    ) -> Disclaimer:
        """
        Get a disclaimer of the specified type.

        Args:
            disclaimer_type: Type of disclaimer to get
            context: Context variables for template substitution

        Returns:
            Disclaimer object
        """
        template = self.templates.get(disclaimer_type, self.templates[DisclaimerType.GENERAL])

        # Format text with context
        text = template['text']
        if context:
            try:
                text = text.format(**context)
            except KeyError as e:
                logger.warning(f"Missing context variable for disclaimer: {e}")

        disclaimer_id = hashlib.sha256(
            f"{disclaimer_type.value}:{datetime.now().isoformat()}".encode()
        ).hexdigest()[:16]

        return Disclaimer(
            disclaimer_id=disclaimer_id,
            disclaimer_type=disclaimer_type,
            severity=template['severity'],
            title=template['title'],
            text=text.strip(),
            must_acknowledge=template['must_acknowledge'],
            context=context or {}
        )

    def get_disclaimers_for_prediction(
        self,
        prediction: Dict[str, Any],
        vehicle_coverage: Optional[Dict[str, Any]] = None
    ) -> List[Disclaimer]:
        """
        Get all relevant disclaimers for a prediction.

        Args:
            prediction: The prediction data
            vehicle_coverage: Vehicle coverage information

        Returns:
            List of Disclaimer objects that must be shown
        """
        disclaimers = []

        # Always include general prediction disclaimer
        disclaimers.append(self.get_disclaimer(DisclaimerType.PREDICTION))

        # Check for critical failure
        failure_type = prediction.get('failure_type', '')
        criticality = prediction.get('criticality', '')

        if criticality == 'critical' or failure_type in ['fuel_pump', 'coolant_system', 'transmission']:
            disclaimers.append(self.get_disclaimer(
                DisclaimerType.CRITICAL_FAILURE,
                {'failure_type': failure_type.replace('_', ' ').title()}
            ))

        # Check confidence level
        confidence = prediction.get('confidence', 1.0)
        if confidence < 0.5:
            disclaimers.append(self.get_disclaimer(
                DisclaimerType.LOW_CONFIDENCE,
                {'confidence': round(confidence * 100, 1)}
            ))

        # Check vehicle coverage
        if vehicle_coverage:
            coverage_level = vehicle_coverage.get('coverage_level', '')
            if coverage_level in ['unsupported', 'minimal']:
                disclaimers.append(self.get_disclaimer(
                    DisclaimerType.UNSUPPORTED_VEHICLE,
                    {
                        'year': vehicle_coverage.get('year', 'Unknown'),
                        'make': vehicle_coverage.get('make', 'Unknown'),
                        'model': vehicle_coverage.get('model', 'Unknown')
                    }
                ))

        # Add professional advice if probability is high
        failure_prob = prediction.get('failure_probability', 0)
        if failure_prob > 0.5:
            disclaimers.append(self.get_disclaimer(
                DisclaimerType.PROFESSIONAL_ADVICE,
                {
                    'prediction_summary': f"{failure_type} failure predicted",
                    'confidence': round(confidence * 100, 1)
                }
            ))

        return disclaimers

    def get_legal_disclaimer(self) -> Disclaimer:
        """Get the legal disclaimer (required on first use)."""
        return self.get_disclaimer(DisclaimerType.LEGAL)

    def check_acknowledgment_required(
        self,
        disclaimer: Disclaimer,
        user_id: str
    ) -> bool:
        """
        Check if user needs to acknowledge this disclaimer.

        Args:
            disclaimer: The disclaimer to check
            user_id: User identifier

        Returns:
            True if acknowledgment is required
        """
        if not disclaimer.must_acknowledge:
            return False

        key = f"{user_id}:{disclaimer.disclaimer_type.value}"

        # Check if already acknowledged
        if key in self._acknowledgments:
            return False

        # Check session-based showing
        session_key = f"session:{disclaimer.disclaimer_type.value}"
        template = self.templates.get(disclaimer.disclaimer_type)

        if template:
            frequency = template.get('show_frequency', 'always')

            if frequency == 'once_per_session' and session_key in self._session_shown:
                return False

        return True

    def record_acknowledgment(
        self,
        disclaimer: Disclaimer,
        user_id: str,
        ip_address: Optional[str] = None,
        device_info: Optional[str] = None
    ) -> DisclaimerAcknowledgment:
        """
        Record user acknowledgment of a disclaimer.

        Args:
            disclaimer: The disclaimer being acknowledged
            user_id: User identifier
            ip_address: IP address for audit
            device_info: Device info for audit

        Returns:
            Acknowledgment record
        """
        ack_id = hashlib.sha256(
            f"{disclaimer.disclaimer_id}:{user_id}:{datetime.now().isoformat()}".encode()
        ).hexdigest()[:16]

        acknowledgment = DisclaimerAcknowledgment(
            acknowledgment_id=ack_id,
            disclaimer_id=disclaimer.disclaimer_id,
            disclaimer_type=disclaimer.disclaimer_type.value,
            user_id=user_id,
            acknowledged_at=datetime.now().isoformat(),
            ip_address=ip_address,
            device_info=device_info
        )

        key = f"{user_id}:{disclaimer.disclaimer_type.value}"
        self._acknowledgments[key] = acknowledgment

        # Track in session
        session_key = f"session:{disclaimer.disclaimer_type.value}"
        self._session_shown.add(session_key)

        self._save_acknowledgments()

        logger.info(f"Disclaimer {disclaimer.disclaimer_type.value} acknowledged by {user_id}")

        return acknowledgment

    def has_acknowledged_legal(self, user_id: str) -> bool:
        """Check if user has acknowledged legal disclaimer."""
        key = f"{user_id}:{DisclaimerType.LEGAL.value}"
        return key in self._acknowledgments

    def format_disclaimer_for_display(
        self,
        disclaimer: Disclaimer,
        format_type: str = 'text'
    ) -> str:
        """
        Format disclaimer for display.

        Args:
            disclaimer: Disclaimer to format
            format_type: 'text', 'html', or 'markdown'

        Returns:
            Formatted disclaimer string
        """
        if format_type == 'html':
            severity_class = disclaimer.severity.value
            return f"""
<div class="disclaimer disclaimer-{severity_class}">
    <h3 class="disclaimer-title">{disclaimer.title}</h3>
    <div class="disclaimer-text">{disclaimer.text.replace(chr(10), '<br>')}</div>
    {f'<div class="disclaimer-acknowledge">Please acknowledge to continue</div>' if disclaimer.must_acknowledge else ''}
</div>
"""
        elif format_type == 'markdown':
            severity_icon = {
                DisclaimerSeverity.CRITICAL: "🚨",
                DisclaimerSeverity.WARNING: "⚠️",
                DisclaimerSeverity.INFO: "ℹ️",
                DisclaimerSeverity.LEGAL: "⚖️"
            }.get(disclaimer.severity, "")

            return f"""
{severity_icon} **{disclaimer.title}**

{disclaimer.text}

{"---\n*Acknowledgment required to continue*" if disclaimer.must_acknowledge else ""}
"""
        else:
            # Plain text
            border = "=" * 60
            return f"""
{border}
{disclaimer.title.upper()}
{border}

{disclaimer.text}

{"[ACKNOWLEDGMENT REQUIRED]" if disclaimer.must_acknowledge else ""}
{border}
"""

    def get_mandatory_disclaimers_text(self) -> str:
        """Get concatenated text of all mandatory disclaimers."""
        mandatory_types = [
            DisclaimerType.GENERAL,
            DisclaimerType.LEGAL
        ]

        texts = []
        for dtype in mandatory_types:
            disclaimer = self.get_disclaimer(dtype)
            texts.append(self.format_disclaimer_for_display(disclaimer, 'text'))

        return "\n\n".join(texts)


# =============================================================================
# SINGLETON ACCESS
# =============================================================================

_manager_instance: Optional[SafetyDisclaimerManager] = None


def get_disclaimer_manager() -> SafetyDisclaimerManager:
    """Get or create singleton manager instance."""
    global _manager_instance
    if _manager_instance is None:
        _manager_instance = SafetyDisclaimerManager()
    return _manager_instance


def get_prediction_disclaimers(
    prediction: Dict[str, Any],
    vehicle_coverage: Optional[Dict[str, Any]] = None
) -> List[Disclaimer]:
    """Convenience function to get disclaimers for a prediction."""
    manager = get_disclaimer_manager()
    return manager.get_disclaimers_for_prediction(prediction, vehicle_coverage)


def format_disclaimer(disclaimer: Disclaimer, format_type: str = 'text') -> str:
    """Convenience function to format a disclaimer."""
    manager = get_disclaimer_manager()
    return manager.format_disclaimer_for_display(disclaimer, format_type)
