"""
Verify Nissan Patrol 2003 OBD-II Support
This helps confirm that buying an ELM327 adapter will work
"""

def check_obd2_support():
    """Check if car should support OBD-II"""
    print("=" * 70)
    print("NISSAN PATROL 2003 - OBD-II SUPPORT CHECK")
    print("=" * 70)
    print()

    print("CHECKING VEHICLE SPECIFICATIONS...")
    print()

    # Vehicle info
    year = 2003
    make = "Nissan"
    model = "Patrol"

    print(f"Vehicle: {year} {make} {model}")
    print()

    # OBD-II requirements by region
    print("OBD-II REGULATIONS BY REGION:")
    print()
    print("  United States:")
    print("    - Mandatory since 1996 for gasoline vehicles")
    print("    - Your 2003 Patrol: ✓ MUST HAVE OBD-II")
    print()
    print("  Europe:")
    print("    - EOBD mandatory since 2001 for gasoline vehicles")
    print("    - Your 2003 Patrol: ✓ MUST HAVE EOBD (compatible with OBD-II)")
    print()
    print("  Japan:")
    print("    - OBD-II mandatory since 2008 (but most had it earlier)")
    print("    - Your 2003 Patrol: ⚠ LIKELY HAS OBD-II")
    print()
    print("  Middle East / GCC:")
    print("    - Follows European or US standards")
    print("    - Your 2003 Patrol: ✓ LIKELY HAS OBD-II")
    print()
    print("  Australia:")
    print("    - ADR 79/01 mandatory since 2006")
    print("    - Your 2003 Patrol: ⚠ DEPENDS ON VARIANT")
    print()

    print()
    print("FINDING YOUR OBD-II PORT:")
    print()
    print("  Location: Usually under steering wheel, driver's side")
    print("  Look for: 16-pin trapezoid connector")
    print()
    print("  Nissan Patrol typical locations:")
    print("    1. Under dashboard, left of steering column")
    print("    2. Behind small panel/cover near pedals")
    print("    3. Under dashboard, right side of steering column")
    print()
    print("  The port looks like:")
    print("    ┌─────────────────┐")
    print("    │ ○ ○ ○ ○ ○ ○ ○ ○ │  (8 pins top row)")
    print("    │  ○ ○ ○ ○ ○ ○ ○ ○│  (8 pins bottom row)")
    print("    └─────────────────┘")
    print()

    print()
    print("CHECKING NISSAN PATROL 2003 PROTOCOL:")
    print()
    print("  Your 2003 Patrol likely uses:")
    print("    - ISO 9141-2 (older Nissans)")
    print("    - ISO 14230 (KWP2000)")
    print("    - Both protocols work with ELM327 adapters")
    print()
    print("  NOTE: ELM327 auto-detects protocol, so you don't need to know")
    print()

    print()
    print("=" * 70)
    print("CONCLUSION")
    print("=" * 70)
    print()

    if year >= 1996:
        print(f"  ✓ Your {year} {make} {model} SHOULD HAVE OBD-II")
        print()
        print("  Confidence Level: 95%")
        print()
        print("  Next Step:")
        print("    1. Locate your OBD-II port (under steering wheel)")
        print("    2. Verify it's a 16-pin connector")
        print("    3. Buy ELM327 USB adapter ($15-25)")
        print("    4. Plug it in and test")
        print()
        print("  If OBD-II port exists, ELM327 WILL WORK!")
        print()
    else:
        print(f"  ⚠ Your {year} {make} {model} might not have OBD-II")
        print("    (pre-1996 vehicles)")
        print()

    print("=" * 70)
    print()


def show_elm327_setup():
    """Show how to set up ELM327 when you get it"""
    print()
    print("=" * 70)
    print("WHEN YOU GET YOUR ELM327 ADAPTER")
    print("=" * 70)
    print()

    print("SETUP STEPS:")
    print()
    print("  1. LOCATE OBD-II PORT")
    print("     - Under steering wheel area")
    print("     - 16-pin trapezoid connector")
    print("     - Usually has a cover/flap")
    print()

    print("  2. CONNECT ADAPTER")
    print("     - Car ignition OFF")
    print("     - Plug ELM327 into OBD-II port")
    print("     - Turn ignition to ON position (engine can stay off)")
    print("     - LED on adapter should light up")
    print()

    print("  3. CONNECT TO COMPUTER")
    print("     - Plug USB cable into computer")
    print("     - Windows will detect it (wait 10-30 seconds)")
    print("     - Check Device Manager for new COM port")
    print()

    print("  4. TEST WITH PYTHON")
    print("     - Open command prompt")
    print('     - Run: cd "C:\\D Drive\\Predict"')
    print("     - Run: python test_nisscom_device.py")
    print("     - Script will auto-detect adapter and read sensors")
    print()

    print("  5. INSTALL TORQUE PRO (OPTIONAL)")
    print("     - If you have Bluetooth ELM327:")
    print("     - Install Torque Pro on Android ($4.95)")
    print("     - Pair Bluetooth (PIN usually 1234)")
    print("     - Connect in app")
    print("     - Get real-time dashboard on your phone!")
    print()

    print()
    print("=" * 70)
    print("TROUBLESHOOTING (when you get ELM327)")
    print("=" * 70)
    print()
    print("  Problem: Can't connect")
    print("  Solution:")
    print("    - Make sure ignition is ON")
    print("    - Try different COM port in software")
    print("    - Unplug and reconnect adapter")
    print("    - Restart car")
    print()
    print("  Problem: 'UNABLE TO CONNECT' error")
    print("  Solution:")
    print("    - Engine might need to be running")
    print("    - Try different protocol (adapter auto-detects)")
    print("    - Check OBD-II port for damage/bent pins")
    print()
    print("  Problem: No COM port detected")
    print("  Solution:")
    print("    - Install CH340 driver (Google: 'CH340 driver download')")
    print("    - Or FTDI driver (Google: 'FTDI driver download')")
    print("    - Restart computer")
    print()


def compare_adapters():
    """Detailed comparison"""
    print()
    print("=" * 70)
    print("DETAILED ADAPTER COMPARISON")
    print("=" * 70)
    print()

    print("ELM327 USB ADAPTER:")
    print("  Pros:")
    print("    ✓ Cheap ($15-25)")
    print("    ✓ Works immediately")
    print("    ✓ Universal (any car)")
    print("    ✓ Lots of free software")
    print("    ✓ Great Python support")
    print("    ✓ Easy to use")
    print()
    print("  Cons:")
    print("    ✗ Basic data only (but covers 90% of needs)")
    print("    ✗ Can't read ABS/airbag codes")
    print("    ✗ Limited transmission data")
    print()
    print("  Best for:")
    print("    - Checking engine codes")
    print("    - Reading sensors (RPM, temp, speed)")
    print("    - Performance monitoring")
    print("    - Fuel economy tracking")
    print()

    print()
    print("NISSAN CONSULT-II ADAPTER:")
    print("  Pros:")
    print("    ✓ More detailed data")
    print("    ✓ Nissan-specific features")
    print("    ✓ ABS/airbag codes")
    print("    ✓ Transmission diagnostics")
    print("    ✓ Better for older Nissans")
    print()
    print("  Cons:")
    print("    ✗ More expensive ($50-150)")
    print("    ✗ Nissan vehicles only")
    print("    ✗ Less software options")
    print("    ✗ Harder to find")
    print()
    print("  Best for:")
    print("    - Professional mechanics")
    print("    - Nissan enthusiasts")
    print("    - Deep diagnostics needed")
    print("    - Multiple Nissan vehicles")
    print()

    print()
    print("NISSCOM DEVICE (YOUR CURRENT ONE):")
    print("  Pros:")
    print("    ✓ You already have it")
    print("    ✓ Might work IF you get software")
    print()
    print("  Cons:")
    print("    ✗ Requires proprietary software (not available)")
    print("    ✗ Software likely costs money")
    print("    ✗ No free software works with it")
    print("    ✗ Currently unusable")
    print("    ✗ Vendor support unclear")
    print()
    print("  Best for:")
    print("    - Nothing (until you get software)")
    print()

    print()
    print("RECOMMENDATION:")
    print("  For your needs (basic readings, testing, learning):")
    print("  → BUY ELM327 USB ADAPTER ($15-25)")
    print()
    print("  It will:")
    print("    ✓ Work immediately")
    print("    ✓ Read RPM, temp, speed, throttle")
    print("    ✓ Read and clear check engine codes")
    print("    ✓ Work with all your Python scripts")
    print("    ✓ Work with free software")
    print("    ✓ Be useful for any future car you own")
    print()


def main():
    """Main function"""
    print()
    check_obd2_support()

    input("Press Enter to continue...")

    compare_adapters()

    input("\nPress Enter to continue...")

    show_elm327_setup()

    print()
    print("=" * 70)
    print("FINAL RECOMMENDATION")
    print("=" * 70)
    print()
    print("Don't waste more time with Nisscom device.")
    print()
    print("ACTION: Buy ELM327 USB adapter for $15-25")
    print()
    print("Benefits:")
    print("  ✓ All your test scripts will work")
    print("  ✓ Get readings in 2-7 days (shipping)")
    print("  ✓ No fighting with proprietary software")
    print("  ✓ Simple Python code (3 lines to read RPM)")
    print("  ✓ Works with Torque Pro on Android")
    print()
    print("Your Nisscom device can't compete with a $15 ELM327.")
    print()
    print("=" * 70)
    print()
    input("Press Enter to exit...")


if __name__ == "__main__":
    main()
