"""add user_id to vehicle_guardians and subscriptions table

Revision ID: 9243035df623
Revises: ae4fe080b7b0
Create Date: 2026-02-14 21:13:51.386108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9243035df623'
down_revision: Union[str, None] = 'ae4fe080b7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('google_purchase_token', sa.Text(), nullable=True),
    sa.Column('google_product_id', sa.String(length=100), nullable=True),
    sa.Column('google_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.Column('cancelled_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.add_column('guardian_commands', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('guardian_commands', 'guardian_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('location_requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('location_requests', 'guardian_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('vehicle_guardians', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('vehicle_guardians', 'guardian_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_guardians', 'guardian_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('vehicle_guardians', 'user_id')
    op.alter_column('location_requests', 'guardian_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('location_requests', 'user_id')
    op.alter_column('guardian_commands', 'guardian_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('guardian_commands', 'user_id')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
