"""add daily_vehicle_stats

Revision ID: ae4fe080b7b0
Revises: 7012346db23a
Create Date: 2026-02-14 20:06:13.556142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4fe080b7b0'
down_revision: Union[str, None] = '7012346db23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_vehicle_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('max_speed_kmh', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('max_coolant_temp_c', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('avg_speed_kmh', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('total_distance_km', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('total_fuel_consumed_l', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('data_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'date', name='uq_daily_stats_vehicle_date')
    )
    op.create_index('idx_daily_stats_profile', 'daily_vehicle_stats', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_daily_stats_profile', table_name='daily_vehicle_stats')
    op.drop_table('daily_vehicle_stats')
    # ### end Alembic commands ###
