"""add_fleet_request_fields

Revision ID: ddaede4258e7
Revises: e5f7a9b1c3d5
Create Date: 2026-02-25 21:55:08.889485
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddaede4258e7'
down_revision: Union[str, None] = 'e5f7a9b1c3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fleet_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'driver'::character varying"))
    op.alter_column('fleet_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('fleets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('tier_upgrade_requests', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('tier_upgrade_requests', sa.Column('fleet_size', sa.String(length=50), nullable=True))
    op.alter_column('vehicle_research', 'created_at',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vehicle_research', 'updated_at',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_research', 'updated_at',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vehicle_research', 'created_at',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('tier_upgrade_requests', 'fleet_size')
    op.drop_column('tier_upgrade_requests', 'company_name')
    op.alter_column('fleets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('fleet_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('fleet_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'driver'::character varying"))
    # ### end Alembic commands ###
